spring:
  application:
    name: url-trim

server:
  port: ${PORT:8080}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: dadlnajelkfnwfnjqfoqioiqnjnfjkwenfjnfwjnqlkqlf
  expiration: 172800000

frontend-url: